## Conversion Driver Analysis
- Multiple rigorous methods (statistical tests, ML models, engagement segmentation); correct interpretation; honest findings even if null.

In [2]:
# Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Import Datasets

In [3]:
df_activity_pivot_flag = pd.read_csv(
    "C:/Users/HP PC/Documents/jacob_dbt_projects/trial_activation_analysis/dataset/exports/df_activity_pivot_flag.csv"
)

df_activity_pivot_flag.head(3)

,ORGANIZATION_ID,Absence.Request.Approved,Absence.Request.Created,Absence.Request.Rejected,Break.Activate.Finished,Break.Activate.Started,Communication.Message.Created,Integration.Xero.PayrollExport.Synced,Mobile.Schedule.Loaded,PunchClock.Entry.Edited,...,Scheduling.Shift.AssignmentChanged,Scheduling.Shift.Created,Scheduling.ShiftHandover.Accepted,Scheduling.ShiftHandover.Created,Scheduling.ShiftSwap.Accepted,Scheduling.ShiftSwap.Created,Scheduling.Template.ApplyModal.Applied,Shift.View.Opened,ShiftDetails.View.Opened,Timesheets.BulkApprove.Confirmed
0,0040dd9ab132b92d5d04bc3acf14d2e2,1,1,1,0,0,1,0,1,1,...,1,1,0,0,0,0,1,0,1,0
1,00456fd86311b6095ad05f7e31758f0d,0,0,0,0,0,1,0,1,0,...,1,1,0,0,0,0,0,0,0,0
2,007d48a2bc006e6eac0348c788d26dfd,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df_organization = pd.read_csv(
    "C:/Users/HP PC/Documents/jacob_dbt_projects/trial_activation_analysis/dataset/exports/df_organization.csv"
)

df_organization.head(3)

,ORGANIZATION_ID,CONVERTED,CONVERTED_AT,TRIAL_START,TRIAL_END,days_to_convert,trial_start_month,total_events,unique_activity_count,active_days
0,0040dd9ab132b92d5d04bc3acf14d2e2,False,NaN,2024-03-27 10:11:39,2024-04-26 10:11:39,NaN,3,1004,14,11
1,00456fd86311b6095ad05f7e31758f0d,False,NaN,2024-01-11 13:44:36,2024-02-10 13:44:36,NaN,1,6,4,1
2,007d48a2bc006e6eac0348c788d26dfd,False,NaN,2024-03-16 22:58:07,2024-04-15 22:58:07,NaN,3,5,2,3

In [5]:
df_organization_act_count = pd.read_csv(
    "C:/Users/HP PC/Documents/jacob_dbt_projects/trial_activation_analysis/dataset/exports/df_organization_act_count.csv"
)

df_organization_act_count.head(3)

,ORGANIZATION_ID,CONVERTED,CONVERTED_AT,TRIAL_START,TRIAL_END,days_to_convert,trial_start_month,total_events,unique_activity_count,active_days,...,Scheduling.Shift.AssignmentChanged,Scheduling.Shift.Created,Scheduling.ShiftHandover.Accepted,Scheduling.ShiftHandover.Created,Scheduling.ShiftSwap.Accepted,Scheduling.ShiftSwap.Created,Scheduling.Template.ApplyModal.Applied,Shift.View.Opened,ShiftDetails.View.Opened,Timesheets.BulkApprove.Confirmed
0,0040dd9ab132b92d5d04bc3acf14d2e2,False,NaN,2024-03-27 10:11:39,2024-04-26 10:11:39,NaN,3,1004,14,11,...,384,576,0,0,0,0,10,0,1,0
1,00456fd86311b6095ad05f7e31758f0d,False,NaN,2024-01-11 13:44:36,2024-02-10 13:44:36,NaN,1,6,4,1,...,3,1,0,0,0,0,0,0,0,0
2,007d48a2bc006e6eac0348c788d26dfd,False,NaN,2024-03-16 22:58:07,2024-04-15 22:58:07,NaN,3,5,2,3,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df_organization_act_flag = pd.read_csv(
    "C:/Users/HP PC/Documents/jacob_dbt_projects/trial_activation_analysis/dataset/exports/df_organization_act_flag.csv"
)

df_organization_act_flag.head(3)

,ORGANIZATION_ID,CONVERTED,CONVERTED_AT,TRIAL_START,TRIAL_END,days_to_convert,trial_start_month,total_events,unique_activity_count,active_days,...,Scheduling.Shift.AssignmentChanged,Scheduling.Shift.Created,Scheduling.ShiftHandover.Accepted,Scheduling.ShiftHandover.Created,Scheduling.ShiftSwap.Accepted,Scheduling.ShiftSwap.Created,Scheduling.Template.ApplyModal.Applied,Shift.View.Opened,ShiftDetails.View.Opened,Timesheets.BulkApprove.Confirmed
0,0040dd9ab132b92d5d04bc3acf14d2e2,False,NaN,2024-03-27 10:11:39,2024-04-26 10:11:39,NaN,3,1004,14,11,...,1,1,0,0,0,0,1,0,1,0
1,00456fd86311b6095ad05f7e31758f0d,False,NaN,2024-01-11 13:44:36,2024-02-10 13:44:36,NaN,1,6,4,1,...,1,1,0,0,0,0,0,0,0,0
2,007d48a2bc006e6eac0348c788d26dfd,False,NaN,2024-03-16 22:58:07,2024-04-15 22:58:07,NaN,3,5,2,3,...,0,0,0,0,0,0,0,0,0,0

In [18]:
df_trial = pd.read_csv(
    "C:/Users/HP PC/Documents/jacob_dbt_projects/trial_activation_analysis/dataset/exports/df_trial.csv"
)

df_trial.head(3)

,ORGANIZATION_ID,ACTIVITY_NAME,TIMESTAMP,CONVERTED,CONVERTED_AT,TRIAL_START,TRIAL_END
0,0040dd9ab132b92d5d04bc3acf14d2e2,Scheduling.Shift.Created,2024-03-27 11:03:53,False,NaN,2024-03-27 10:11:39,2024-04-26 10:11:39
1,0040dd9ab132b92d5d04bc3acf14d2e2,Scheduling.Shift.Created,2024-03-27 11:04:52,False,NaN,2024-03-27 10:11:39,2024-04-26 10:11:39
2,0040dd9ab132b92d5d04bc3acf14d2e2,Scheduling.Shift.Created,2024-03-27 11:04:53,False,NaN,2024-03-27 10:11:39,2024-04-26 10:11:39

### Chi-square test of Independence

In [8]:
import pandas as pd
from scipy.stats import chi2_contingency

# Get activity columns from pivot table
activity_columns = [
    col for col in df_activity_pivot_flag.columns
    if col != 'ORGANIZATION_ID'
]

# Overall conversion rate (used internally only)
overall_conversion_rate = (
    df_organization['CONVERTED'].mean()
)

results = []

for activity in activity_columns:

    # Create contingency table
    contingency = pd.crosstab(
        df_organization_act_flag[activity],
        df_organization_act_flag['CONVERTED']
    )

    # Ensure full 2x2 structure
    contingency = contingency.reindex(
        index=[0, 1],
        columns=[False, True],
        fill_value=0
    )

    # Run Chi-square test
    chi2, p_value, dof, expected = chi2_contingency(contingency)

    # Conversion rate after usage
    users_after_usage = contingency.loc[1].sum()

    if users_after_usage > 0:
        conversion_rate_after = (
            contingency.loc[1, True]
            / users_after_usage
        )
    else:
        conversion_rate_after = 0

    # Lift Ratio
    if overall_conversion_rate > 0:
        lift_ratio = (
            conversion_rate_after
            / overall_conversion_rate
        )
    else:
        lift_ratio = 0

    results.append({
        'ACTIVITY_NAME': activity,

        'CHI_SQUARE_STAT': round(chi2, 3),

        'P_VALUE': round(p_value, 5),

        'CONVERSION_RATE_AFTER_USAGE (%)':
            round(conversion_rate_after * 100, 1),

        'LIFT_RATIO':
            round(lift_ratio, 2)
    })

# Convert to DataFrame
chi_activity_results = pd.DataFrame(results)

# Sort by statistical significance
chi_activity_results = (
    chi_activity_results
    .sort_values('P_VALUE')
    .reset_index(drop=True)
)

chi_activity_results

,ACTIVITY_NAME,CHI_SQUARE_STAT,P_VALUE,CONVERSION_RATE_AFTER_USAGE (%),LIFT_RATIO
0,Communication.Message.Created,1.994,0.15789,16.6,0.78
1,Scheduling.OpenShiftRequest.Created,1.609,0.20465,30.2,1.42
2,Timesheets.BulkApprove.Confirmed,1.605,0.20518,0.0,0.00
3,PunchClock.Entry.Edited,0.845,0.35788,0.0,0.00
4,Scheduling.Shift.Created,0.772,0.37951,21.8,1.02
5,Scheduling.Template.ApplyModal.Applied,0.748,0.38720,25.0,1.17
6,Scheduling.ShiftHandover.Created,0.730,0.39281,36.4,1.71
7,Scheduling.ShiftSwap.Accepted,0.607,0.43577,0.0,0.00
8,Scheduling.ShiftSwap.Created,0.564,0.45263,8.3,0.39
9,PunchClockEndNote.Add.Completed,0.474,0.49098,14.3,0.67
10,PunchClock.PunchedIn,0.227,0.63403,22.7,1.07
11,Scheduling.ShiftHandover.Accepted,0.225,0.63491,33.3,1.56
12,Revenue.Budgets.Created,0.186,0.66589,0.0,0.00
13,Absence.Request.Rejected,0.114,0.73524,28.6,1.34
14,PunchClockStartNote.Add.Completed,0.097,0.75495,15.8,0.74
15,Scheduling.OpenShiftRequest.Approved,0.039,0.84360,0.0,0.00
16,PunchClock.PunchedOut,0.032,0.85829,12.5,0.59
17,Scheduling.Shift.Approved,0.027,0.86913,22.0,1.03
18,Scheduling.Shift.AssignmentChanged,0.003,0.95352,21.6,1.01
19,ShiftDetails.View.Opened,0.001,0.97138,20.0,0.94
20,Break.Activate.Finished,0.000,1.00000,16.7,0.78
21,Mobile.Schedule.Loaded,0.000,1.00000,21.3,1.00
22,Integration.Xero.PayrollExport.Synced,0.000,1.00000,16.7,0.78
23,Absence.Request.Approved,0.000,1.00000,20.0,0.94
24,Scheduling.Availability.Set,0.000,1.00000,22.0,1.03
25,Break.Activate.Started,0.000,1.00000,16.7,0.78
26,Absence.Request.Created,0.000,1.00000,20.5,0.96
27,Shift.View.Opened,0.000,1.00000,0.0,0.00

### Mann–Whitney U test for Numeric Features

#### Outcome:
- All features had p-values > 0.05
- Shows **no statistically significant differences** between converted and non-converted users.

In [9]:
import pandas as pd
from scipy.stats import mannwhitneyu

# Updated list of numeric columns (remove 'days_to_convert' due to nulls)
numeric_cols = [
    'trial_start_month',
    'total_events',
    'unique_activity_count',
    'active_days'
]

# Split into groups
group_true = df_organization[df_organization['CONVERTED'] == True]
group_false = df_organization[df_organization['CONVERTED'] == False]

results = []

# Loop through each feature
for col in numeric_cols:

    # Drop missing values
    g1 = group_true[col].dropna()
    g0 = group_false[col].dropna()

    # Skip empty columns
    if len(g1) == 0 or len(g0) == 0:
        continue

    # Mann–Whitney U test
    u_stat, u_p = mannwhitneyu(
        g1,
        g0,
        alternative='two-sided'
    )

    # Store results with mean and median
    results.append({
        'feature': col,

        'median_converted': round(g1.median(), 2),
        'median_not_converted': round(g0.median(), 2),

        'mean_converted': round(g1.mean(), 2),
        'mean_not_converted': round(g0.mean(), 2),

        'u_stat': round(u_stat, 2),
        'p_value': round(u_p, 5)
    })

# Convert to dataframe
results_df = pd.DataFrame(results)

# Sort by strongest statistical evidence
results_df = results_df.sort_values(
    by='p_value'
).reset_index(drop=True)

results_df

,feature,median_converted,median_not_converted,mean_converted,mean_not_converted,u_stat,p_value
0,trial_start_month,2.0,2.0,1.94,2.03,73371.5,0.14252
1,unique_activity_count,2.0,2.0,2.78,2.78,79822.0,0.65015
2,active_days,1.0,1.0,4.21,4.29,78981.5,0.81978
3,total_events,8.0,8.0,107.88,106.15,78944.5,0.85130

### Logistics Regression

In [10]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

# Target variable
y = df_organization['CONVERTED'].astype(int)

# Selected numeric features
numeric_features = [
    'total_events',
    'unique_activity_count',
    'active_days',
    'trial_start_month'
]

# Add activity features if needed later
activity_features = [
    # example:
    # 'CREATE_REPORT',
    # 'EXPORT_DATA'
]

selected_features = numeric_features + activity_features

# Create feature matrix
X = df_organization[selected_features].copy()

# Fill missing values
X = X.fillna(0)

# Convert nullable Int64 → float64 (critical fix)
X = X.astype('float64')

# Add intercept
X = sm.add_constant(X)

# Fit logistic regression
model = sm.Logit(y, X)
result = model.fit()

# Extract results
odds_ratios = np.exp(result.params)

logistic_results = pd.DataFrame({
    'Feature': result.params.index,
    'Coefficient': result.params.values,
    'Odds_Ratio': odds_ratios.values,
    'P_Value': result.pvalues.values
})

# Remove intercept
logistic_results = logistic_results[
    logistic_results['Feature'] != 'const'
]

# Sort by statistical importance
logistic_results = logistic_results.sort_values(
    by='P_Value'
).reset_index(drop=True)

logistic_results

Optimization terminated successfully.
         Current function value: 0.516997
         Iterations 5

                 Feature  Coefficient  Odds_Ratio   P_Value
0      trial_start_month    -0.151254    0.859629  0.129738
1            active_days    -0.008825    0.991214  0.630129
2  unique_activity_count     0.015722    1.015846  0.749801
3           total_events     0.000065    1.000065  0.844952

## 3. Trial Goal Definition
- Goals grounded in product-value logic with supporting evidence; realistic completion rates; acknowledged as hypotheses not guaranteed levers.

### Trial Goal 1:
- 5 or more **`Scheduling.Shift.Created`**

In [11]:
# Define activity column
activity_col = 'Scheduling.Shift.Created'

# Define thresholds to test
thresholds = [1, 3, 5]

# Total number of organisations
total_orgs = df_organization_act_count.shape[0]

# Overall conversion rate
overall_conversion_rate = (
    df_organization_act_count['CONVERTED']
    .mean()
)

results = []

# Loop through thresholds
for t in thresholds:

    # Organisations meeting threshold
    used_df = df_organization_act_count[
        df_organization_act_count[activity_col] >= t
    ]

    # Number of organisations using
    num_orgs_used = used_df.shape[0]

    # Skip if no organisations meet threshold
    if num_orgs_used == 0:
        continue

    # Percent of organisations using
    pct_orgs_using = num_orgs_used / total_orgs

    # Number converted
    num_converted = used_df['CONVERTED'].sum()

    # Percent converted after usage
    pct_converted_after_usage = (
        num_converted / num_orgs_used
    )

    # Lift ratio
    lift_ratio = (
        pct_converted_after_usage /
        overall_conversion_rate
    )

    # Label formatting
    if t == 1:
        label = activity_col
    else:
        label = f'>= {t} {activity_col}'

    # Store results
    results.append({
        'ACTIVITY_LEVEL': label,

        'USERS_COUNT': num_orgs_used,

        'COMPLETION_RATE_%': round(
            pct_orgs_using * 100, 2
        ),

        'CONVERTED_AFTER_USAGE': num_converted,

        'CONVERSION_RATE_IF_COMPLETED_%': round(
            pct_converted_after_usage * 100, 2
        ),

        'LIFT_RATIO': round(lift_ratio, 2)
    })

# Convert to dataframe
activity_summary_df = pd.DataFrame(results)

activity_summary_df

,ACTIVITY_LEVEL,USERS_COUNT,COMPLETION_RATE_%,CONVERTED_AFTER_USAGE,CONVERSION_RATE_IF_COMPLETED_%,LIFT_RATIO
0,Scheduling.Shift.Created,848,87.78,185,21.82,1.02
1,>= 3 Scheduling.Shift.Created,563,58.28,120,21.31,1.00
2,>= 5 Scheduling.Shift.Created,450,46.58,98,21.78,1.02

### Trial Goal 2:
- 1 or more **`Scheduling.Template.ApplyModal.Applied`** OR **`Scheduling.Shift.Approved`**

### Scheduling.Template.ApplyModal.Applied

In [12]:
# Define activity column
activity_col = 'Scheduling.Template.ApplyModal.Applied'

# Define thresholds to test
thresholds = [1, 3, 5]

# Total number of organisations
total_orgs = df_organization_act_count.shape[0]

# Overall conversion rate
overall_conversion_rate = (
    df_organization_act_count['CONVERTED']
    .mean()
)

results = []

# Loop through thresholds
for t in thresholds:

    # Organisations meeting threshold
    used_df = df_organization_act_count[
        df_organization_act_count[activity_col] >= t
    ]

    # Number of organisations using
    num_orgs_used = used_df.shape[0]

    # Skip if no organisations meet threshold
    if num_orgs_used == 0:
        continue

    # Percent of organisations using
    pct_orgs_using = num_orgs_used / total_orgs

    # Number converted
    num_converted = used_df['CONVERTED'].sum()

    # Percent converted after usage
    pct_converted_after_usage = (
        num_converted / num_orgs_used
    )

    # Lift ratio
    lift_ratio = (
        pct_converted_after_usage /
        overall_conversion_rate
    )

    # Label formatting
    if t == 1:
        label = activity_col
    else:
        label = f'>= {t} {activity_col}'

    # Store results
    results.append({
        'ACTIVITY_LEVEL': label,

        'USERS_COUNT': num_orgs_used,

        'COMPLETION_RATE_%': round(
            pct_orgs_using * 100, 2
        ),

        'CONVERTED_AFTER_USAGE': num_converted,

        'CONVERSION_RATE_IF_COMPLETED_%': round(
            pct_converted_after_usage * 100, 2
        ),

        'LIFT_RATIO': round(lift_ratio, 2)
    })

# Convert to dataframe
activity_summary_df = pd.DataFrame(results)

activity_summary_df

,ACTIVITY_LEVEL,USERS_COUNT,COMPLETION_RATE_%,CONVERTED_AFTER_USAGE,CONVERSION_RATE_IF_COMPLETED_%,LIFT_RATIO
0,Scheduling.Template.ApplyModal.Applied,108,11.18,27,25.00,1.17
1,>= 3 Scheduling.Template.ApplyModal.Applied,56,5.80,16,28.57,1.34
2,>= 5 Scheduling.Template.ApplyModal.Applied,34,3.52,8,23.53,1.10

### Scheduling.Shift.Approved

In [13]:
# Define activity column
activity_col = 'Scheduling.Shift.Approved'

# Define thresholds to test
thresholds = [1, 3, 5]

# Total number of organisations
total_orgs = df_organization_act_count.shape[0]

# Overall conversion rate
overall_conversion_rate = (
    df_organization_act_count['CONVERTED']
    .mean()
)

results = []

# Loop through thresholds
for t in thresholds:

    # Organisations meeting threshold
    used_df = df_organization_act_count[
        df_organization_act_count[activity_col] >= t
    ]

    # Number of organisations using
    num_orgs_used = used_df.shape[0]

    # Skip if no organisations meet threshold
    if num_orgs_used == 0:
        continue

    # Percent of organisations using
    pct_orgs_using = num_orgs_used / total_orgs

    # Number converted
    num_converted = used_df['CONVERTED'].sum()

    # Percent converted after usage
    pct_converted_after_usage = (
        num_converted / num_orgs_used
    )

    # Lift ratio
    lift_ratio = (
        pct_converted_after_usage /
        overall_conversion_rate
    )

    # Label formatting
    if t == 1:
        label = activity_col
    else:
        label = f'>= {t} {activity_col}'

    # Store results
    results.append({
        'ACTIVITY_LEVEL': label,

        'USERS_COUNT': num_orgs_used,

        'COMPLETION_RATE_%': round(
            pct_orgs_using * 100, 2
        ),

        'CONVERTED_AFTER_USAGE': num_converted,

        'CONVERSION_RATE_IF_COMPLETED_%': round(
            pct_converted_after_usage * 100, 2
        ),

        'LIFT_RATIO': round(lift_ratio, 2)
    })

# Convert to dataframe
activity_summary_df = pd.DataFrame(results)

activity_summary_df

,ACTIVITY_LEVEL,USERS_COUNT,COMPLETION_RATE_%,CONVERTED_AFTER_USAGE,CONVERSION_RATE_IF_COMPLETED_%,LIFT_RATIO
0,Scheduling.Shift.Approved,200,20.70,44,22.00,1.03
1,>= 3 Scheduling.Shift.Approved,111,11.49,27,24.32,1.14
2,>= 5 Scheduling.Shift.Approved,86,8.90,21,24.42,1.15

### **`Scheduling.Template.ApplyModal.Applied`** OR **`Scheduling.Shift.Approved`**

In [14]:
# Define activity columns
activity_1 = 'Scheduling.Template.ApplyModal.Applied'
activity_2 = 'Scheduling.Shift.Approved'

# Define thresholds
thresholds = [1, 3, 5]

# Total organisations
total_orgs = df_organization_act_count.shape[0]

# Overall conversion rate
overall_conversion_rate = (
    df_organization_act_count['CONVERTED']
    .mean()
)

results = []

# Create combined OR activity count
# (sum of both activities)
combined_activity = (
    df_organization_act_count[activity_1] +
    df_organization_act_count[activity_2]
)

# Loop through thresholds
for t in thresholds:

    # Organisations meeting threshold
    used_df = df_organization_act_count[
        combined_activity >= t
    ]

    # Number of organisations using
    num_orgs_used = used_df.shape[0]

    # Skip empty thresholds
    if num_orgs_used == 0:
        continue

    # Percent of organisations using
    pct_orgs_using = num_orgs_used / total_orgs

    # Number converted
    num_converted = used_df['CONVERTED'].sum()

    # Percent converted after usage
    pct_converted_after_usage = (
        num_converted / num_orgs_used
    )

    # Lift ratio
    lift_ratio = (
        pct_converted_after_usage /
        overall_conversion_rate
    )

    # Label
    if t == 1:
        label = f'{activity_1} OR {activity_2}'
    else:
        label = f'>= {t} ({activity_1} OR {activity_2})'

    # Store results
    results.append({
        'ACTIVITY_LEVEL': label,

        'USERS_COUNT': num_orgs_used,

        'COMPLETION_RATE_%': round(
            pct_orgs_using * 100, 2
        ),

        'CONVERTED_AFTER_USAGE': num_converted,

        'CONVERSION_RATE_IF_COMPLETED_%': round(
            pct_converted_after_usage * 100, 2
        ),

        'LIFT_RATIO': round(lift_ratio, 2)
    })

# Convert to dataframe
activity_summary_df = pd.DataFrame(results)

activity_summary_df

,ACTIVITY_LEVEL,USERS_COUNT,COMPLETION_RATE_%,CONVERTED_AFTER_USAGE,CONVERSION_RATE_IF_COMPLETED_%,LIFT_RATIO
0,Scheduling.Template.ApplyModal.Applied OR Sche...,247,25.57,56,22.67,1.06
1,>= 3 (Scheduling.Template.ApplyModal.Applied O...,147,15.22,35,23.81,1.12
2,>= 5 (Scheduling.Template.ApplyModal.Applied O...,114,11.80,28,24.56,1.15

### Trial Goal 3:
- 3 or more **`Mobile.Schedule.Loaded`**

### Mobile.Schedule.Loaded

In [15]:
# Define activity column
activity_col = 'Mobile.Schedule.Loaded'

# Define thresholds
thresholds = [1, 3, 5]

# Total number of organisations
total_orgs = df_organization_act_count.shape[0]

# Overall conversion rate
overall_conversion_rate = (
    df_organization_act_count['CONVERTED']
    .mean()
)

results = []

# Loop through thresholds
for t in thresholds:

    # Organisations meeting threshold
    used_df = df_organization_act_count[
        df_organization_act_count[activity_col] >= t
    ]

    # Number of organisations using
    num_orgs_used = used_df.shape[0]

    # Skip if none meet threshold
    if num_orgs_used == 0:
        continue

    # Percent of organisations using
    pct_orgs_using = num_orgs_used / total_orgs

    # Number converted
    num_converted = used_df['CONVERTED'].sum()

    # Percent converted after usage
    pct_converted_after_usage = (
        num_converted / num_orgs_used
    )

    # Lift ratio
    lift_ratio = (
        pct_converted_after_usage /
        overall_conversion_rate
    )

    # Label formatting
    if t == 1:
        label = activity_col
    else:
        label = f'>= {t} {activity_col}'

    # Store results
    results.append({
        'ACTIVITY_LEVEL': label,

        'USERS_COUNT': num_orgs_used,

        'COMPLETION_RATE_%': round(
            pct_orgs_using * 100, 2
        ),

        'CONVERTED_AFTER_USAGE': num_converted,

        'CONVERSION_RATE_IF_COMPLETED_%': round(
            pct_converted_after_usage * 100, 2
        ),

        'LIFT_RATIO': round(lift_ratio, 2)
    })

# Convert to dataframe
activity_summary_df = pd.DataFrame(results)

activity_summary_df

,ACTIVITY_LEVEL,USERS_COUNT,COMPLETION_RATE_%,CONVERTED_AFTER_USAGE,CONVERSION_RATE_IF_COMPLETED_%,LIFT_RATIO
0,Mobile.Schedule.Loaded,456,47.20,97,21.27,1.00
1,>= 3 Mobile.Schedule.Loaded,348,36.02,77,22.13,1.04
2,>= 5 Mobile.Schedule.Loaded,299,30.95,61,20.40,0.96

### Trial Goal 4:
- 1 or more **`PunchClock.PunchedIn`**

### PunchClock.PunchedIn

In [16]:
# Define activity column
activity_col = 'PunchClock.PunchedIn'

# Define thresholds
thresholds = [1, 3, 5]

# Total number of organisations
total_orgs = df_organization_act_count.shape[0]

# Overall conversion rate
overall_conversion_rate = (
    df_organization_act_count['CONVERTED']
    .mean()
)

results = []

# Loop through thresholds
for t in thresholds:

    # Organisations meeting threshold
    used_df = df_organization_act_count[
        df_organization_act_count[activity_col] >= t
    ]

    # Number of organisations using
    num_orgs_used = used_df.shape[0]

    # Skip if none meet threshold
    if num_orgs_used == 0:
        continue

    # Percent of organisations using
    pct_orgs_using = num_orgs_used / total_orgs

    # Number converted
    num_converted = used_df['CONVERTED'].sum()

    # Percent converted after usage
    pct_converted_after_usage = (
        num_converted / num_orgs_used
    )

    # Lift ratio
    lift_ratio = (
        pct_converted_after_usage /
        overall_conversion_rate
    )

    # Label formatting
    if t == 1:
        label = activity_col
    else:
        label = f'>= {t} {activity_col}'

    # Store results
    results.append({
        'ACTIVITY_LEVEL': label,

        'USERS_COUNT': num_orgs_used,

        'COMPLETION_RATE_%': round(
            pct_orgs_using * 100, 2
        ),

        'CONVERTED_AFTER_USAGE': num_converted,

        'CONVERSION_RATE_IF_COMPLETED_%': round(
            pct_converted_after_usage * 100, 2
        ),

        'LIFT_RATIO': round(lift_ratio, 2)
    })

# Convert to dataframe
activity_summary_df = pd.DataFrame(results)

activity_summary_df

,ACTIVITY_LEVEL,USERS_COUNT,COMPLETION_RATE_%,CONVERTED_AFTER_USAGE,CONVERSION_RATE_IF_COMPLETED_%,LIFT_RATIO
0,PunchClock.PunchedIn,211,21.84,48,22.75,1.07
1,>= 3 PunchClock.PunchedIn,125,12.94,27,21.60,1.01
2,>= 5 PunchClock.PunchedIn,104,10.77,21,20.19,0.95

### total_events_first_7_days

In [55]:
# # Ensure datetime formats
# df_trial['TIMESTAMP'] = pd.to_datetime(df_trial['TIMESTAMP'])
# df_trial['TRIAL_START'] = pd.to_datetime(df_trial['TRIAL_START'])

# # -------- Create total_events_first_7_days -------- #

# total_events_first_7_days = (
#     df_trial[
#         (df_trial['TIMESTAMP'] >= df_trial['TRIAL_START']) &
#         (df_trial['TIMESTAMP'] <
#          df_trial['TRIAL_START'] + pd.Timedelta(days=7))
#     ]
#     .groupby('ORGANIZATION_ID')
#     .size()
#     .rename('total_events_first_7_days')
# )

# # -------- Temporary merge (not saved to original DF) -------- #

# temp_df = (
#     df_organization_act_count[
#         ['ORGANIZATION_ID', 'CONVERTED']
#     ]
#     .merge(
#         total_events_first_7_days,
#         on='ORGANIZATION_ID',
#         how='left'
#     )
# )

# # Replace missing values with 0
# temp_df['total_events_first_7_days'] = (
#     temp_df['total_events_first_7_days']
#     .fillna(0)
# )

# # -------- Threshold Analysis -------- #

# thresholds = [1, 3, 5, 6, 7, 8, 10, 11]

# total_orgs = temp_df.shape[0]

# overall_conversion_rate = (
#     temp_df['CONVERTED']
#     .mean()
# )

# results = []

# for t in thresholds:

#     used_df = temp_df[
#         temp_df['total_events_first_7_days'] >= t
#     ]

#     num_orgs_used = used_df.shape[0]

#     if num_orgs_used == 0:
#         continue

#     pct_orgs_using = num_orgs_used / total_orgs

#     num_converted = used_df['CONVERTED'].sum()

#     pct_converted_after_usage = (
#         num_converted / num_orgs_used
#     )

#     lift_ratio = (
#         pct_converted_after_usage /
#         overall_conversion_rate
#     )

#     if t == 1:
#         label = 'total_events_first_7_days'
#     else:
#         label = f'>= {t} total_events_first_7_days'

#     results.append({
#         'ACTIVITY_LEVEL': label,

#         'USERS_COUNT': num_orgs_used,

#         'COMPLETION_RATE_%': round(
#             pct_orgs_using * 100, 2
#         ),

#         'CONVERTED_AFTER_USAGE': num_converted,

#         'CONVERSION_RATE_IF_COMPLETED_%': round(
#             pct_converted_after_usage * 100, 2
#         ),

#         'LIFT_RATIO': round(lift_ratio, 2)
#     })

# total_events_7d_summary_df = pd.DataFrame(results)

# total_events_7d_summary_df

### Trial Goal 5:
- 3 or more **`unique_activity_count_first_7_days`**

### unique_activity_count_first_7_days

In [19]:
# Ensure datetime formats
df_trial['TIMESTAMP'] = pd.to_datetime(df_trial['TIMESTAMP'])
df_trial['TRIAL_START'] = pd.to_datetime(df_trial['TRIAL_START'])

# -------- Create unique_activity_count_first_7_days -------- #

unique_activity_count_first_7_days = (
    df_trial[
        (df_trial['TIMESTAMP'] >= df_trial['TRIAL_START']) &
        (df_trial['TIMESTAMP'] <
         df_trial['TRIAL_START'] + pd.Timedelta(days=7))
    ]
    .groupby('ORGANIZATION_ID')['ACTIVITY_NAME']
    .nunique()
    .rename('unique_activity_count_first_7_days')
)

# -------- Temporary merge (not saved to original DF) -------- #

temp_df = (
    df_organization_act_count[
        ['ORGANIZATION_ID', 'CONVERTED']
    ]
    .merge(
        unique_activity_count_first_7_days,
        on='ORGANIZATION_ID',
        how='left'
    )
)

# Replace missing values with 0
temp_df['unique_activity_count_first_7_days'] = (
    temp_df['unique_activity_count_first_7_days']
    .fillna(0)
)

# -------- Threshold Analysis -------- #

# Added >= 2 here
thresholds = [1, 2, 3, 5, 10]

total_orgs = temp_df.shape[0]

overall_conversion_rate = (
    temp_df['CONVERTED']
    .mean()
)

results = []

for t in thresholds:

    used_df = temp_df[
        temp_df['unique_activity_count_first_7_days'] >= t
    ]

    num_orgs_used = used_df.shape[0]

    if num_orgs_used == 0:
        continue

    pct_orgs_using = num_orgs_used / total_orgs

    num_converted = used_df['CONVERTED'].sum()

    pct_converted_after_usage = (
        num_converted / num_orgs_used
    )

    lift_ratio = (
        pct_converted_after_usage /
        overall_conversion_rate
    )

    if t == 1:
        label = 'unique_activity_count_first_7_days'
    else:
        label = f'>= {t} unique_activity_count_first_7_days'

    results.append({
        'ACTIVITY_LEVEL': label,

        'USERS_COUNT': num_orgs_used,

        'COMPLETION_RATE_%': round(
            pct_orgs_using * 100, 2
        ),

        'CONVERTED_AFTER_USAGE': num_converted,

        'CONVERSION_RATE_IF_COMPLETED_%': round(
            pct_converted_after_usage * 100, 2
        ),

        'LIFT_RATIO': round(lift_ratio, 2)
    })

unique_activity_7d_summary_df = pd.DataFrame(results)

unique_activity_7d_summary_df

,ACTIVITY_LEVEL,USERS_COUNT,COMPLETION_RATE_%,CONVERTED_AFTER_USAGE,CONVERSION_RATE_IF_COMPLETED_%,LIFT_RATIO
0,unique_activity_count_first_7_days,924,95.65,198,21.43,1.00
1,>= 2 unique_activity_count_first_7_days,523,54.14,112,21.41,1.00
2,>= 3 unique_activity_count_first_7_days,273,28.26,61,22.34,1.05
3,>= 5 unique_activity_count_first_7_days,89,9.21,17,19.10,0.90
4,>= 10 unique_activity_count_first_7_days,3,0.31,0,0.00,0.00